<a href="https://colab.research.google.com/github/ThodupunooriSaiManish/DAV_Assignment_205/blob/main/Machine_Learning_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab1

In [ ]:
import numpy as np

In [ ]:
n=np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=n.reshape(2,5)
print(a)
print()
b=n.reshape(2,-1)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
c=np.arange(10).reshape(2,5)
d=np.arange(10).reshape(5,2)
print(np.dot(c,d))

[[ 60  70]
 [160 195]]


In [ ]:
e=np.arange(11)
f=np.flip(e)
print(f)

[10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
import numpy as np

a = np.eye(3)
b = np.array([[1, 2, 3]])
c = np.vstack((a, b))
print(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 2. 3.]]


In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

diagonal = np.diag(matrix)
print(diagonal)


[1 5 9]


Pandas Exercise-1



In [ ]:
import pandas as pd
#Q9
data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}
index = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=index)
print(Sales)

            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [ ]:
#Q10
# a) Display row labels
print("Row Labels:", Sales.index.tolist())
print()
# b) Display column labels
print("Column Labels:", Sales.columns.tolist())
print()
# c) Display data types of each column
print("Data Types:\n", Sales.dtypes)
print()
# d) Display dimensions, shape, size and values
print("Dimensions:", Sales.ndim)
print("Shape:", Sales.shape)
print("Size:", Sales.size)
print("Values:\n", Sales.values)
print()
# e) Display last two rows
print("Last 2 rows:\n", Sales.tail(2))
print()
# f) Display first two columns
print("First 2 columns:\n", Sales.iloc[:, :2])
print()

Row Labels: [2015, 2016, 2017, 2018, 'Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti', 2018]

Column Labels: ['Shailesh', 'Kusum', 'Vivaan', 'Shruti', 'Sumeet', 2018, 'Madhu', 'Kinshuk', 'Ankit']

Data Types:
 Shailesh    float64
Kusum       float64
Vivaan      float64
Shruti      float64
Sumeet      float64
2018        float64
Madhu       float64
Kinshuk     float64
Ankit       float64
dtype: object

Dimensions: 2
Shape: (10, 9)
Size: 90
Values:
 [[ 12000.  18000.  30000.  45000.  37800.     nan     nan     nan     nan]
 [ 20000.  50000. 100000. 125000.  52000.     nan     nan     nan     nan]
 [ 50000.  60000.  80000.  90000.  78438.     nan     nan     nan     nan]
 [100000. 110000. 340000. 900000.  38852.     nan     nan     nan     nan]
 [    nan     nan     nan     nan     nan 160000.     nan     nan     nan]
 [    nan     nan     nan     nan     nan 110000.     nan     nan     nan]
 [    nan     nan     nan     nan     nan 500000.     nan     nan     nan]
 [    nan     nan     nan

In [ ]:
data_2018 = {
    'Madhu': 160000,
    'Kusum': 110000,
    'Kinshuk': 500000,
    'Ankit': 340000,
    'Shruti': 900000
}
Sales2 = pd.DataFrame(data_2018, index=[2018]).T
print("Sales2 DataFrame:\n", Sales2)

# h) Check if Sales2 is empty
print("Is Sales2 empty?", Sales2.empty)

# a) Append Sales2
Sales = pd.concat([Sales, Sales2], axis=1)
print("After appending Sales2:\n", Sales)

# b) Transpose
Sales = Sales.T
print("Transposed Sales:\n", Sales)

# c) Sales in 2017
print("Sales in 2017:\n", Sales.loc[2017])

# d) Sales by Madhu and Ankit in 2017 and 2018
print("Sales by Madhu and Ankit in 2017 and 2018:\n", Sales.loc[[2017, 2018], ['Madhu', 'Ankit']])

# e) Sales by Shruti in 2016
print("Sales by Shruti in 2016:", Sales.at[2016, 'Shruti'])

# f) Add Sumeet’s data
Sales['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]
print("After adding Sumeet:\n", Sales)

# g) Delete year 2014
Sales = Sales.drop(index=2014)
print("After deleting 2014:\n", Sales)

# h) Delete Kinshuk
Sales = Sales.drop(columns='Kinshuk')
print("After deleting Kinshuk:\n", Sales)

# i) Rename Ankit to Vivaan and Madhu to Shailesh
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print("After renaming:\n", Sales)

# j) Update sale of Shailesh in 2018 to 100000
Sales.at[2018, 'Shailesh'] = 100000
print("After updating Shailesh 2018 sale:\n", Sales)

# k) Write to CSV (without row/column labels)
Sales.to_csv("SalesFigures.csv", index=False, header=False)

# l) Read from CSV and update labels
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)

# Set same row and column labels as Sales
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print("SalesRetrieved:\n", SalesRetrieved)


Sales2 DataFrame:
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000
Is Sales2 empty? False
After appending Sales2:
             2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000
Transposed Sales:
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0
Sales in 2017:
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64
Sales by Madhu and Ankit in 2017 and 2018:
          Madhu     Ankit

In [ ]:
#Exercise-2,Q13
import pandas as pd

# Create DataFrame
data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

Product = pd.DataFrame(data)
print("Product DataFrame:\n", Product)
# New rows to add
new_data = {
    'Item': ['AC', 'TV'],
    'Company': ['LG', 'SONY'],
    'Rupees': [16000, 13000],
    'USD': [850, 720]
}

new_rows = pd.DataFrame(new_data)
Product = pd.concat([Product, new_rows], ignore_index=True)
print("Updated Product DataFrame:\n", Product)
# Filter LG TVs
lg_tv = Product[(Product['Item'] == 'TV') & (Product['Company'] == 'LG')]
max_price = lg_tv['Rupees'].max()
print("Maximum price of LG TV:", max_price)

total_rupees = Product['Rupees'].sum()
print("Total Rupees of all products:", total_rupees)

sony_usd_median = Product[Product['Company'] == 'SONY']['USD'].median()
print("Median USD for Sony products:", sony_usd_median)

Product_sorted = Product.sort_values(by='Rupees')
print("Sorted Product DataFrame:\n", Product_sorted)


Product DataFrame:
   Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
Updated Product DataFrame:
   Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   AC        LG   16000  850
5   TV      SONY   13000  720
Maximum price of LG TV: 15000
Total Rupees of all products: 80000
Median USD for Sony products: 735.0
Sorted Product DataFrame:
   Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
5   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
4   AC        LG   16000  850


In [ ]:
from sqlalchemy import create_engine

# Define connection parameters (update with your DB credentials)
user = 'root'
password = 'your_password'
host = 'localhost'
database = 'your_database'

# Create SQLAlchemy engine
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")

# Write the sorted DataFrame to MySQL table named 'ProductSorted'
Product_sorted.to_sql('ProductSorted', con=engine, if_exists='replace', index=False)
print("Data transferred to MySQL table 'ProductSorted'")

# Example new data
new_data2 = {
    'Item': ['Washing Machine', 'TV'],
    'Company': ['Samsung', 'Panasonic'],
    'Rupees': [21000, 17000],
    'USD': [950, 810]
}
Product_new = pd.DataFrame(new_data2)

# Transfer to MySQL table named 'NewProduct'
Product_new.to_sql('NewProduct', con=engine, if_exists='replace', index=False)
print("New DataFrame transferred to MySQL table 'NewProduct'")
